export const QUESTIONS_LOAD = 'QUESTIONS_LOAD'
export const QUESTIONS_LOAD_SUCCESS = 'QUESTIONS_LOAD_SUCCESS'
export const QUESTIONS_LOAD_FAILURE = 'QUESTIONS_LOAD_FAILURE'

export const ANSWERS_LOAD = 'ANSWERS_LOAD'
export const ANSWERS_LOAD_SUCCESS = 'ANSWERS_LOAD_SUCCESS'
export const ANSWERS_LOAD_FAILURE = 'ANSWERS_LOAD_FAILURE'
